Update manager.py and node.py
plathanus-tech/python-jr-test pull request #5
Opened 2022-02-09 22:21 UTC by gdomingosg

Submitting the completed test for evaluation.

2022-02-10 10:18 UTC, leandrodesouzadev requested changes

2022-02-10 10:18 UTC, leandrodesouzadev commented on manager.py
> +    def remove(self, node: object) -> None:
Olá, bom dia!
O método __repr__ é usado apenas para representar o objeto como um texto, não devendo ser utilizado para realizar operações. Corrija a implementação dos métodos `remove` e `remove_cascade`.

2022-02-10 10:18 UTC, leandrodesouzadev commented on node.py
> +    def id_num(self) -> int:
Os Métodos id_num e parent_num não foram solicitados e não estão sendo utilizados em nenhum local. Está correto?

2022-02-14 17:23 UTC, gdomingosg commented on node.py
> +    def id_num(self) -> int:
Adicionei os métodos para realizar alguns testes e acabei esquecendo de removê-los.

2022-02-14 22:32 UTC, gdomingosg commented on nodes/manager.py
> +    def remove(self, node: T1) -> None:
Métodos atualizados

2022-03-10 23:04 UTC, closed without merging